- cmd/provider-services/cmd/root.go
- cmd/provider-services/cmd/run.go
- go.mod
- go.sum
> feat(client): integrate akash tx/query commands

- .github/workflows/codecov.yaml
> fix(ci): remove extra colon from run-on

- .github/workflows/release.yaml
> ci: remove release dry-run on main branch

- .github/workflows/release-dry-run.yaml
- make/releasing.mk
> ci(release): use gh action default token

- .github/workflows/release-dry-run.yaml
- .github/workflows/release.yaml
- cmd/provider-services/cmd/migrate/v0_14tov0_16.go
- cmd/provider-services/cmd/run.go
- gateway/rest/router_test.go
- gateway/rest/server.go
- go.mod
- go.sum
- integration/e2e_test.go
- integration/escrow_monitor_test.go
- integration/persistentstorage_test.go
- integration/test_helpers.go
- make/lint.mk
- operator/hostnameoperator/hostname_operator.go
- operator/inventory/cmd.go
- operator/ipoperator/ip_operator.go
> ci(release): make temporary tag for release dry-run to work on main branch

- cmd/provider-services/cmd/root.go
move node related status/migrate under "node"
refs ovrclk/engineering#635
> fix(commands): create node subcommand

- make/init.mk
> fix(build): remove quotes from PATH append

- .goreleaser.yaml
> fix(build): static exe for linux hosts

- go.mod
- go.sum
> feat: upgrade akash to v0.18.0

- .github/workflows/release.yaml
- script/is_prerelease.sh
> feat(ci): send event to ovrclk/homebrew-tap once release is out

- pkg/apis/akash.network/crd.yaml
- pkg/apis/akash.network/v2beta1/types.go
> fix(provider): restore the command field in the manifest

- cluster/kube/client.go
- cluster/kube/deploy_test.go
- cluster/kube/k8s_integration_test.go
- cmd/provider-services/cmd/run.go
- make/init.mk
- make/releasing.mk
- operator/hostnameoperator/hostname_operator.go
- operator/ipoperator/ip_operator.go
> fix: fail provider start if lease namespace is not found

- make/releasing.mk
> fix(build): unifi release options with akash repo

- go.mod
- go.sum
> fix(RPC): enable websocket via TLS

- .github/workflows/concommits.yaml
> feat(ci): enable validation of commit messages

- script/semver.sh
> fix(scripts): remove redundant exit

- go.mod
- go.sum
> feat(akash): upgrade to v0.20.0

- .github/workflows/release.yaml
> ci(release): checkout codebase to validate ref for homebrew notify

- .github/workflows/release.yaml
> ci(release): use sha as ref for homebrew notify

- .github/workflows/release.yaml
> ci(release): hardcode homebrew ref to refs/heads/master

- .github/workflows/release.yaml
- Makefile
- script/is_prerelease.sh
> refactor(stripts): use exit code as result check instead of string

- .github/workflows/wip.yaml
> ci: add WIP action

- .github/workflows/release-dry-run.yaml
> ci(release): run release-dry on pr

- .github/workflows/wip.yaml
> ci(wip): fix syntax

- .github/workflows/wip.yaml
> ci(wip): use akash-network/wip-check

- .goreleaser-docker-amd64.yaml
- .goreleaser-docker-arm64.yaml
- .goreleaser.yaml
- _docs/kustomize/akash-operator-hostname/deployment.yaml
- _docs/kustomize/akash-operator-ip/deployment.yaml
- _docs/kustomize/akash-provider/deployment.yaml
- _docs/kustomize/redis/kustomization.yaml
- _docs/kustomize/redis/service.yaml
- _docs/kustomize/redis/statefulset.yaml
- _docs/kustomize/templates/akash-operator-hostname/docker-image.yaml
- _docs/kustomize/templates/akash-operator-inventory/docker-image.yaml
- _docs/kustomize/templates/akash-operator-ip/docker-image.yaml
- _docs/kustomize/templates/akash-provider/docker-image.yaml
- _docs/kustomize/templates/redis/kustomization.yaml
- _run/common-kind.mk
- make/releasing.mk
> refactor(build): allow build docker images to custom registry

- _docs/kustomize/akash-provider/deployment.yaml
- _docs/kustomize/akash-provider/kustomization.yaml
refs akash-network/support#6
Signed-off-by: Andrey Arapov <andrey@akash.network>
> refactor(provider): trust-node flag is long gone

- balance_checker.go
- client/broadcaster/serial.go
- cmd/provider-services/cmd/run.go
> feat: prioritize bid messages when broadcasting

- _docs/kustomize/akash-operator-hostname/deployment.yaml
- _docs/kustomize/akash-operator-ip/deployment.yaml
- _docs/kustomize/akash-provider/deployment.yaml
- _docs/kustomize/templates/akash-operator-hostname/docker-image.yaml
- _docs/kustomize/templates/akash-operator-inventory/docker-image.yaml
- _docs/kustomize/templates/akash-operator-ip/docker-image.yaml
- _docs/kustomize/templates/akash-provider/docker-image.yaml
- _run/common-kind.mk
- make/releasing.mk
> fix: rename ghrc image to provider

- bidengine/order.go
- bidengine/order_test.go
- bidengine/pricing_test.go
- bidengine/provider_attributes.go
- bidengine/provider_attributes_test.go
- bidengine/service.go
- cluster/kube/builder/netpol.go
- cluster/kube/builder/service.go
- cluster/kube/builder/workload.go
- cluster/kube/client_exec_test.go
- cluster/kube/deploy_test.go
- cluster/monitor.go
- cluster/types/v1beta2/reservation.go
- cluster/types/v1beta2/types.go
- cmd/provider-services/cmd/helpers.go
- cmd/provider-services/cmd/leaseEvents.go
- cmd/provider-services/cmd/leaseLogs.go
- cmd/provider-services/cmd/manifest.go
- cmd/provider-services/cmd/root.go
- config.go
- gateway/rest/client_shell.go
- gateway/rest/integration_test.go
- gateway/rest/middleware.go
- gateway/rest/router.go
- gateway/rest/router_migrate_test.go
- manifest/watchdog_test.go
- operator/hostnameoperator/hostname_operator_test.go
- operator/ipoperator/ip_operator_test.go
- session/session.go
- testutil/provider/provider.go
> ci: gofmt sources

- .github/workflows/k8s-integration.yaml
> ci: install qemu for k8s integration

- .github/workflows/k8s-integration.yaml
> ci: fix ingress target name

- .github/workflows/k8s-integration.yaml
- _run/common-kind.mk
- _run/common-kube.mk
- _run/kube/Makefile
- script/setup-kube.sh
> ci: set kind cluster name via env

- go.mod
- go.sum
> fix: bump akash v0.23.0-rc6

- cluster/kube/builder/workload.go
- cluster/kube/client.go
- testutil/manifest/v2beta2/manifest_app.go
> fix: set GPU to 0 in manifest generator

- go.mod
- go.sum
> fix: bump akash to v0.23.0-rc7

- cluster/kube/builder/workload.go
> fix: set custom runtime if GPU is requested

- cluster/kube/builder/builder.go
- cluster/kube/builder/deployment.go
- cluster/kube/builder/statefulset.go
- cluster/kube/builder/workload.go
> fix(cluster): runtimeClassName was ignored due to post config

- script/install_dev_dependencies.sh
> fix: echo status of dev dependency

- cluster/client.go
- cluster/inventory.go
- cluster/kube/inventory.go
> fix: check if GPU resource is nil during reservation

- operator/inventory/cmd.go
> refactor(operator/inventory): remove redundant select

- .github/workflows/release.yaml
> ci: use check-name for wait in dry-run check

- _run/common-kube.mk
- make/init.mk
> fix(make): check host bash version and error if major < 4

- _run/common-helm.mk
- _run/common-kube.mk
> fix(_run): add install of helm charts to the cluster-setup

- .github/workflows/cron-integration-tests.yaml
- .github/workflows/integration-tests.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- combine all test and check build workflows into single
- trigger release if pushed by tag and all tests pass
> ci: consolidate workflows into fewer pieces

- bidengine/order.go
- bidengine/pricing.go
- bidengine/shellscript.go
* expose currency to bid engine
> feat: take rate, multi-currency

- README.md
integrations is now part of the tests group
> docs: remove interations tests badge

- make/init.mk
> chore: bump mockery to v2.32.0

- _run/common-kind.mk
- _run/common-kube.mk
- _run/common.mk
- script/setup-kind.sh
- script/setup-kube.sh
> feat: setup-kube parse options

- operator/inventory/rancher.go
fixes akash-network/support#268
> fix(inventory): skip persistent volume if it references non existing storageclass

- bidengine/order_test.go
- operator/inventory/node-discovery.go
brings fix for incorrect inventory calculations when pod is deleted
> fix: bump akash-api
